#!/bin/bash

logfile='/home/dfelinto/log/mysql'

PATH=/usr/sbin:/usr/bin:/sbin:/bin

if [[ ! "$(service mysql status)" =~ "start/running" ]]
then
  echo "MySQL Failed:" `date` >> $logfile
  service mysql start
fi
